---
title: "Importancia variables"
author: "VSC"
date: "12/5/2021"
output: html_document
---

```{r}

library(readr)
library(rsample)
library(recipes)
library(parsnip)
library(workflows)
library(purrr)
path <- "C:/Users/valsc/Desktop/Notas ITAM/Aprendizaje_maquina/Final/"
datos <- read_csv(paste(path,"desersion.csv", sep = ""),
                 col_types =  "cdcdcccdcccccccccccccccccccccccccccccdcccccccccccccccccccccccccc")
                   
```


```{r, fig.height=10, fig.width = 10}
set.seed(232)
desertor_split <- initial_split(datos, prop = 0.75)
desertor_entrena <- training(casas_split)
desertor_pr <- testing(desertor_split)

receta <- recipe(desertor ~ 
           tabaco+alcohol+ p40_12+p40_15,
           data = desertor_entrena) %>% 
    step_interact( ~ p12_1:p12_10)%>%
    step_dummy(all_nominal_predictors()) %>%
    step_zv(all_predictors()) #step_zv  remove variables that contain only a single value.
```



```{r}
prep(receta, desertor_entrena) %>% juice() %>% dim()
```

```{r}

modelo_boosting <- boost_tree(learn_rate = 0.1, trees = 1000, 
                              mtry = 5, tree_depth = 3, sample_size = 0.8) %>%
  set_mode("classification") %>% 
  set_args(objective = "binary:logistic")
flujo <- workflow() %>% 
  add_recipe(receta) %>% 
  add_model(modelo_boosting)
flujo_fit <- fit(flujo, desertor_entrena)


```


```{r, message=FALSE, include=FALSE, warning=FALSE}
devtools::install_github("christophM/iml", 
                         ref = "48dfc4eb847ff2bc267570316c662acb36ff9d52",
                         force = TRUE)
```

```{r, message = FALSE}
library(iml)
# necesitamos esta función para el paquete iml

pred_iml <- function(model, newdata){
   predict(model, new_data = newdata) |> pull(.pred_class)
}

predictor <- Predictor$new(model = flujo_fit, data = desertor_pr, 
  y = "desertor", predict.fun = pred_iml)


```

```{r, fig.width =6, fig.height= 8}
vars_usadas <- extract_preprocessor(flujo_fit) |> pluck("var_info") |>
  filter(role == "predictor") |> 
  pull(variable)

imp_boosting <- FeatureImp$new(predictor, loss = "ce",  
                             compare = "difference", n.repetitions = 5, features = vars_usadas)

importancias <- imp_boosting$results |> 
    mutate(feature = fct_reorder(feature, importance))

ggplot(importancias, aes(x = feature, y = importance)) +
    geom_hline(yintercept = 0, colour = "salmon") +
    geom_point() + coord_flip()


```


